sonar-project.properties
This configuration covers all 4 of origin repos:
* https://github.com/stolostron/registration/blob/main/sonar-project.properties
* https://github.com/stolostron/registration-operator/blob/main/sonar-project.properties
* https://github.com/stolostron/placement/blob/main/sonar-project.properties
* https://github.com/stolostron/work/blob/main/sonar-project.properties
=> Add sonar configuration.

.tekton/addon-manager-pull-request.yaml, .tekton/addon-manager-push.yaml, .tekton/placement-pull-request.yaml, .tekton/placement-push.yaml, .tekton/registration-operator-pull-request.yaml, .tekton/registration-operator-push.yaml, .tekton/registration-pull-request.yaml, .tekton/registration-push.yaml, .tekton/work-pull-request.yaml, .tekton/work-push.yaml, build/Dockerfile.addon.rhtap, build/Dockerfile.placement.rhtap, build/Dockerfile.registration-operator.rhtap, build/Dockerfile.registration.rhtap, build/Dockerfile.work.rhtap
https://issues.redhat.com/browse/ACM-7262
Fixes #
=> :seedling: Add dockerfile for rhtap

pkg/work/spoke/controllers/finalizercontroller/unmanaged_appliedmanifestwork_controller.go, pkg/work/spoke/options.go
The related issue: https://issues.redhat.com/browse/ACM-8926
Fixes #
=> 🐛 increase the eviction-grace-period to 24 hours

pkg/operator/operators/klusterlet/options.go
Fixes #. https://issues.redhat.com/browse/ACM-8799
=> :bug: fix the incorrect externalManagedKubeConfig secret name

build/Dockerfile.addon.rhtap, build/Dockerfile.placement.rhtap, build/Dockerfile.registration-operator.rhtap, build/Dockerfile.registration.rhtap, build/Dockerfile.work.rhtap
=> Bump up go version to 1.21 for rhtap dockerfiles

deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml, deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml, go.mod, go.sum, manifests/klusterlet/managed/klusterlet-work-clusterrole-execution.yaml, manifests/klusterlet/management/klusterlet-agent-deployment.yaml, manifests/klusterlet/management/klusterlet-registration-deployment.yaml, manifests/klusterlet/management/klusterlet-work-deployment.yaml, pkg/operator/helpers/helpers.go, pkg/operator/helpers/helpers_test.go, pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go, test/integration/operator/klusterlet_test.go, vendor/modules.txt, vendor/open-cluster-management.io/api/crdsv1beta1/0001_00_operator.open-cluster-management.io_klusterlets.crd.yaml, vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml, vendor/open-cluster-management.io/api/operator/v1/types_klusterlet.go, vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go
=> [cherry-pick]: ✨ support configuration of the agent priorityclass (#358)

pkg/registration/spoke/addon/registration_controller.go
Fixes: https://issues.redhat.com/browse/ACM-10093
Note: this fix is only a workaround, and is not included in the main branch or backplane-2.6+.
=> :bug: Add hubHash in addon client cert secret as a workaround for issue-10093

pkg/work/spoke/options.go
Fixes: https://issues.redhat.com/browse/ACM-10267
Related fix PR: https://github.com/stolostron/managedcluster-import-controller/pull/318
=> :bug: Fix: add default value for workloadsourcedriver.

pkg/work/spoke/controllers/finalizercontroller/unmanaged_appliedmanifestwork_controller.go, pkg/work/spoke/options.go
Fixes # https://issues.redhat.com/browse/ACM-10407
=> 🐛 [backplane-2.5] increase the eviction-grace-period to 24 hours

.tekton/OWNERS
=> :seedling: Add OWNERS for konflux config

.tekton/addon-manager-mce-25-pull-request.yaml, .tekton/addon-manager-mce-25-push.yaml, .tekton/placement-mce-25-pull-request.yaml, .tekton/placement-mce-25-push.yaml, .tekton/registration-mce-25-pull-request.yaml, .tekton/registration-mce-25-push.yaml, .tekton/registration-operator-mce-25-pull-request.yaml, .tekton/registration-operator-mce-25-push.yaml, .tekton/work-mce-25-pull-request.yaml, .tekton/work-mce-25-push.yaml
=> Konflux migration from 0.3 to 0.4

pkg/registration/hub/lease/controller.go, pkg/registration/spoke/managedcluster/status_controller.go
cherry-pick #496
Fixes #https://issues.redhat.com/browse/ACM-11800
=> [2.6] Refine the cluster available event messages (#496)

pkg/addon/templateagent/registration.go, pkg/addon/templateagent/template_agent.go, pkg/addon/templateagent/template_agent_test.go
=> 🐛 Check if template is nil when getting the addon agent registration namespace (#500)

.github/workflows/e2e.yml, pkg/operator/helpers/sa_syncer.go, pkg/operator/helpers/sa_syncer_test.go, pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go, test/e2e/common.go
cherrypick https://github.com/open-cluster-management-io/ocm/pull/504
Fixes #https://issues.redhat.com/browse/ACM-12018
=> 🐛 Refresh external managed token secret if service account is deleted

pkg/registration/spoke/registration/registration.go, pkg/registration/spoke/spokeagent.go
Fixes # https://issues.redhat.com/browse/ACM-12190
=> 🐛 compare additional data during bootstraping

pkg/addon/templateagent/template_agent.go, pkg/addon/templateagent/template_agent_test.go, pkg/addon/templateagent/values.go, pkg/addon/templateagent/values_test.go
cherry-pick https://github.com/open-cluster-management-io/ocm/pull/533
Fixes #
=> 🐛 Add install namespace to built in values

pkg/registration/spoke/health_checker.go, pkg/registration/spoke/health_checker_test.go, test/integration/registration/spokeagent_rebootstrap_test.go
=> 🐛 [bp-2.6] Restart immediately if the bootstrap kubeconfig changes

.tekton/addon-manager-mce-26-pull-request.yaml, .tekton/addon-manager-mce-26-push.yaml, .tekton/placement-mce-26-pull-request.yaml, .tekton/placement-mce-26-push.yaml, .tekton/registration-mce-26-pull-request.yaml, .tekton/registration-mce-26-push.yaml, .tekton/registration-operator-mce-26-pull-request.yaml, .tekton/registration-operator-mce-26-push.yaml, .tekton/work-mce-26-pull-request.yaml, .tekton/work-mce-26-push.yaml
=> 🌱 [2.6] Konflux migration to 0.2

.tekton/addon-manager-mce-25-pull-request.yaml, .tekton/addon-manager-mce-25-push.yaml, .tekton/placement-mce-25-pull-request.yaml, .tekton/placement-mce-25-push.yaml, .tekton/registration-mce-25-pull-request.yaml, .tekton/registration-mce-25-push.yaml, .tekton/registration-operator-mce-25-pull-request.yaml, .tekton/registration-operator-mce-25-push.yaml, .tekton/work-mce-25-pull-request.yaml, .tekton/work-mce-25-push.yaml
=> [2.5] konflux migration to 0.2

.github/workflows/e2e.yml, pkg/operator/helpers/sa_syncer.go, pkg/operator/helpers/sa_syncer_test.go, pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go, test/e2e/common.go
cherry-pick https://github.com/open-cluster-management-io/ocm/pull/458 https://github.com/open-cluster-management-io/ocm/pull/504
Fixes #https://issues.redhat.com/browse/ACM-13704
=> 🐛 [bp-2.5] Refresh external managed token secret if service account is deleted 

pkg/registration/helpers/testing/testinghelpers.go, pkg/work/helper/helpers.go, test/integration/util/assertion.go, test/integration/util/unstructured.go, test/integration/work/work_test.go
Fixes #
https://issues.redhat.com/browse/ACM-11733
=> skip namespace in resourceMeta for cluster scoped resource (#324)

pkg/registration/hub/manifests/rbac/managedcluster-clusterrole.yaml, pkg/registration/hub/manifests/rbac/managedcluster-clusterrolebinding.yaml, pkg/registration/hub/manifests/rbac/managedcluster-registration-rolebinding.yaml, pkg/registration/hub/manifests/rbac/managedcluster-work-rolebinding.yaml
Fixes # https://issues.redhat.com/browse/ACM-14299
=> :bug: [cherry-pick] fix the cluster name is digital (#621)

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler_test.go, pkg/addon/controllers/addonconfiguration/graph.go
Fixes #https://issues.redhat.com/browse/ACM-14853
=> :bug: [backplane-2.6] fix the mca override cma configs issues

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler_test.go, pkg/addon/controllers/addonconfiguration/graph.go
Cherry pick https://github.com/open-cluster-management-io/ocm/pull/649
Fixes https://issues.redhat.com/browse/ACM-14863
=> 🐛 [backplane-2.7] fix the mca override cma configs issues

.tekton/addon-manager-mce-27-pull-request.yaml, .tekton/addon-manager-mce-27-push.yaml, .tekton/placement-mce-27-pull-request.yaml, .tekton/placement-mce-27-push.yaml, .tekton/registration-mce-27-pull-request.yaml, .tekton/registration-mce-27-push.yaml, .tekton/registration-operator-mce-27-pull-request.yaml, .tekton/registration-operator-mce-27-push.yaml, .tekton/work-mce-27-pull-request.yaml, .tekton/work-mce-27-push.yaml, build/Dockerfile.addon.rhtap, build/Dockerfile.placement.rhtap, build/Dockerfile.registration-operator.rhtap, build/Dockerfile.registration.rhtap, build/Dockerfile.work.rhtap
=> 🌱 konflux: migration from 0.1 to 0.2

manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml, pkg/addon/controllers/addontemplate/controller.go, pkg/addon/manager.go, pkg/addon/templateagent/registration.go, pkg/addon/templateagent/registration_test.go, pkg/addon/templateagent/template_agent.go, pkg/addon/templateagent/template_agent_test.go
=> 🐛 [mce-2.7] Only bind the agent role for the addon group

manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml, pkg/addon/controllers/addontemplate/controller.go, pkg/addon/manager.go, pkg/addon/templateagent/registration.go, pkg/addon/templateagent/registration_test.go, pkg/addon/templateagent/template_agent.go, pkg/addon/templateagent/template_agent_test.go
* Only bind the agent role for the addon group
* Update addon rolebinding
* Start an addon informor for each addon
---------
Fixes #https://issues.redhat.com/browse/ACM-16058
=> 🐛 [mce-2.4] Only bind the agent role for the addon group

hack/e2e_flaky_error_test.sh, manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml, pkg/addon/controllers/addontemplate/controller.go, pkg/addon/manager.go, pkg/addon/templateagent/registration.go, pkg/addon/templateagent/registration_test.go, pkg/addon/templateagent/template_agent.go, pkg/addon/templateagent/template_agent_test.go, test/e2e/addonmanagement_test.go, test/e2e/manifests/addon/addon_template.yaml
Fixes #https://issues.redhat.com/browse/ACM-16005
=> 🐛 [mce-2.6] Only bind the agent role for the addon group

.tekton/addon-manager-mce-28-pull-request.yaml, .tekton/addon-manager-mce-28-push.yaml, .tekton/placement-mce-28-pull-request.yaml, .tekton/placement-mce-28-push.yaml, .tekton/registration-mce-28-pull-request.yaml, .tekton/registration-mce-28-push.yaml, .tekton/registration-operator-mce-28-pull-request.yaml, .tekton/registration-operator-mce-28-push.yaml, .tekton/work-mce-28-pull-request.yaml, .tekton/work-mce-28-push.yaml
This PR:
- Formatting all tekton files
- Update konflux CEL from backplane-2.8 to main
=> :seedling: [main] update konflux files

pkg/registration/hub/lease/clocksynccontroller.go, pkg/registration/hub/lease/clocksynccontroller_test.go, pkg/registration/spoke/managedcluster/status_controller.go, test/integration/registration/managedcluster_lease_test.go
=> Revert "Agents stop update managedcluster status when clock is out of sync. (…"

deploy/cluster-manager/chart/cluster-manager/templates/_helpers.tpl, deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml, deploy/cluster-manager/chart/cluster-manager/templates/operator.yaml, deploy/cluster-manager/chart/cluster-manager/values.yaml, deploy/klusterlet/chart/klusterlet/templates/_helpers.tpl, deploy/klusterlet/chart/klusterlet/templates/klusterlet.yaml, deploy/klusterlet/chart/klusterlet/templates/operator.yaml, deploy/klusterlet/chart/klusterlet/values.yaml, test/e2e-test.mk
Fix e2e error: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stolostron_ocm/195/pull-ci-stolostron-ocm-backplane-2.7-e2e/1876893201445425152
Fixes #
=> Use e2e images instead of latest (#756)

pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go, pkg/work/spoke/spokeagent.go
The related issue: https://issues.redhat.com/browse/ACM-17275
Fixes #
=> 🐛 fix work agent performance issue

.tekton/addon-manager-mce-28-pull-request.yaml, .tekton/addon-manager-mce-28-push.yaml, .tekton/placement-mce-28-pull-request.yaml, .tekton/placement-mce-28-push.yaml, .tekton/registration-mce-28-pull-request.yaml, .tekton/registration-mce-28-push.yaml, .tekton/registration-operator-mce-28-pull-request.yaml, .tekton/registration-operator-mce-28-push.yaml, .tekton/work-mce-28-pull-request.yaml, .tekton/work-mce-28-push.yaml, build/Dockerfile.addon.rhtap, build/Dockerfile.placement.rhtap, build/Dockerfile.registration-operator.rhtap, build/Dockerfile.registration.rhtap, build/Dockerfile.work.rhtap
=> 🌱 Enable hermetic builds

.tekton/addon-manager-mce-28-pull-request.yaml, .tekton/addon-manager-mce-28-push.yaml, .tekton/placement-mce-28-pull-request.yaml, .tekton/placement-mce-28-push.yaml, .tekton/registration-mce-28-pull-request.yaml, .tekton/registration-mce-28-push.yaml, .tekton/registration-operator-mce-28-pull-request.yaml, .tekton/registration-operator-mce-28-push.yaml, .tekton/work-mce-28-pull-request.yaml, .tekton/work-mce-28-push.yaml
=> :seedling: [backplane-2.8] update konflux files

pkg/registration/register/csr/options.go
The related issue: https://issues.redhat.com/browse/ACM-19327
Fixes #
=> Increase the CSR threshold

.github/renovate.json5, .github/workflows/renovate-config-validator.yaml
- configure dockerfile path
- enable gomod update only for released branch(backplane-2.8,2.7,2.6,25), not for main and the current branch
- auto add labels
Fixes #
=> 🌱 Add renovate config file

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
=> 🌱 Modify Konflux config for migration

.github/workflows/cleanup-stale-branches.yml
=> :sparkles: Add: clean up branches.

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
=> :seedling:  Change tekton target branch to backplane-2.9.

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
Fixes https://issues.redhat.com/browse/ACM-21383
=> :seedling:  Upgrade rpms-signature-scan.

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
Fixes https://issues.redhat.com/browse/ACM-21383
=> :seedling: Upgrade rpms signature scan[MCE 2.9]

build/Dockerfile.addon.rhtap, build/Dockerfile.placement.rhtap, build/Dockerfile.registration-operator.rhtap, build/Dockerfile.registration.rhtap, build/Dockerfile.work.rhtap
Fixes https://issues.redhat.com/browse/ACM-21381
=> Remove OS and ARCH in dockerfile.rhtap MCE 2.9

renovate.json5
=> Renovate update for backplane-2.9

build/Dockerfile.registration-operator.rhtap
Fixes https://issues.redhat.com/browse/ACM-21721
=> hardcode CI version to unblock konflux build

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
=> [mce-2.9] update konflux images

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
=> 🌱 Update konflux references

.tekton/addon-manager-mce-29-pull-request.yaml, .tekton/addon-manager-mce-29-push.yaml, .tekton/placement-mce-29-pull-request.yaml, .tekton/placement-mce-29-push.yaml, .tekton/registration-mce-29-pull-request.yaml, .tekton/registration-mce-29-push.yaml, .tekton/registration-operator-mce-29-pull-request.yaml, .tekton/registration-operator-mce-29-push.yaml, .tekton/work-mce-29-pull-request.yaml, .tekton/work-mce-29-push.yaml
=> 🌱 [mce-2.9] Update konflux references

.tekton/addon-manager-mce-210-push.yaml, .tekton/placement-mce-210-push.yaml, .tekton/registration-mce-210-push.yaml, .tekton/registration-operator-mce-210-push.yaml, .tekton/work-mce-210-push.yaml
=> 🌱 Send slack notification to the forum-acm-konflux-pipeline-status channel
